In [ ]:
import numpy as np 
# list
number = [10.20,30,40,50] 

In [5]:
number = np.array([10,20,30,40,50])
print(number)
print(type(number))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [6]:
# multipy evry number by 2 
result = number * 2 
print(number)

[10 20 30 40 50]


In [10]:
print(number+5)
print(number - 5)
print(number * 5)
print(number/2)

[15 25 35 45 55]
[ 5 15 25 35 45]
[ 50 100 150 200 250]
[ 5. 10. 15. 20. 25.]


In [11]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(data)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [13]:
print(number.ndim)
print(data.ndim)

1
2


In [14]:
print(data.shape)

(3, 3)


In [15]:
print(data.size)

9


In [ ]:
print(data.dtype)
# Common NumPy data types include:

# int
# float
# bool
# str

int64


In [20]:
print(number[0])
print(number[1])
print(number[2])
print(number[3])
print(number[4])

10
20
30
40
50


In [22]:
print(number[-1])
print(number[-2])

50
40


In [ ]:
print(number[1:4])
# array[start:stop]

[20 30 40]


In [25]:
print(number[:3])

[10 20 30]


In [ ]:
print(data[1, 1])
# data[row, column]

50


In [28]:
print(data[1])
print(data[2])

[40 50 60]
[70 80 90]


In [ ]:
# To get the first column:

print(data[:,0])

[10 40 70]


In [30]:
print(data[:, 1])

[20 50 80]


In [36]:
a = np.zeros((3,4))
print(a)
a=  np.ones((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [39]:
number = np.arange(0,20,2)
number

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
number = np.random.rand(5)
number

array([0.27667633, 0.85979986, 0.97403524, 0.98009432, 0.38680206])

In [42]:
numbers = np.random.rand(3, 4)

print(numbers)

[[0.05651821 0.25451804 0.10595907 0.84447379]
 [0.70251478 0.56765129 0.71412282 0.36050168]
 [0.20074091 0.37070262 0.43862301 0.49669619]]


In [ ]:
numbers = np.random.randint(1, 100, 10)
# This generates 10 random integers from 1 to 99.
print(numbers)

[ 7 31 73 87  4 64 60 67 30 73]


In [46]:
print(np.square(numbers))
print(np.exp(numbers))
print(np.log(numbers))

[  49  961 5329 7569   16 4096 3600 4489  900 5329]
[1.09663316e+03 2.90488497e+13 5.05239363e+31 6.07603023e+37
 5.45981500e+01 6.23514908e+27 1.14200739e+26 1.25236317e+29
 1.06864746e+13 5.05239363e+31]
[1.94591015 3.4339872  4.29045944 4.46590812 1.38629436 4.15888308
 4.09434456 4.20469262 3.40119738 4.29045944]


In [48]:
print(numbers.sum())

496


In [49]:
marks = np.array([70, 80, 90, 60, 75])

print(np.median(marks))

75.0


In [56]:
print(np.max(marks))
print(np.min(marks))

print(marks.max())
print(marks.min())

90
60
90
60


In [58]:
number = np.array([10,20,30,40,50])
print(number)

[10 20 30 40 50]


In [59]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [60]:
print(np.sum(data))

450


In [62]:

print(np.sum(data , axis=0))
print(np.sum(data , axis=1))

[120 150 180]
[ 60 150 240]


In [64]:
number = np.arange(1,13)
print(number)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [66]:
data= number.reshape(3,4)
print(data)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
numbers = np.array([10, 25, 30, 45, 50, 65])

print(numbers> 40)
# =>This is called Boolean indexing.
print(numbers[numbers > 40])

[False False False  True  True  True]
[45 50 65]


In [72]:
numbers = np.array([10, 20, 30, 40, 50, 60, 70])
result = numbers[(numbers > 20) & (numbers < 60)]
print(result)

[30 40 50]


In [73]:
numbers = np.array([50, 10, 40, 20, 30])

print(np.sort(numbers))


[10 20 30 40 50]


In [75]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.concatenate((a,b))
print(result)

[1 2 3 4 5 6]


In [ ]:
a = np.array([10, 20, 30])
b =  a 
b[0] =100 

print(b)
print(a)
# Both variables refer to the same underlying array.

[100  20  30]
[100  20  30]


In [79]:
a = np.array([10, 20, 30])

b = a.copy()
b[0] = 100 

print(a)
print(b)

[10 20 30]
[100  20  30]


In [80]:
months = np.array([
    "Jan", "Feb", "Mar", "Apr", "May"
])

sales = np.array([
    12000, 15000, 13000, 18000, 21000
])

In [81]:
print(np.mean(sales))
print(np.max(sales))
print(np.min(sales))

15800.0
21000
12000


In [102]:
# Create an array containing numbers 10 to 50.

a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [89]:
a.shape

(40,)

In [90]:
a.size

40

In [92]:
a.mean()
a.max()
a.min()

np.int64(10)

In [93]:
print(a[:3])

[10 11 12]


In [ ]:
print(a[a > 30])



[31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [105]:
a = np.arange(1,21).reshape(4,5)

print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [109]:
print(np.sum(a , axis=1))

[15 40 65 90]


In [110]:
print(np.sum(a , axis=0))

[34 38 42 46 50]
